name: Buildah Build
  # You may pin to the exact commit or the version.
  # uses: redhat-actions/buildah-build@27067e030d458b26cbcef5b1cb342d1eee65a92e
uses: redhat-actions/buildah-build@v1
  with:
    # The name (reference) of the image to build
    image: 
    # The tag of the image to build
    tag: # optional, default is latest
    # The base image to use to create a new container image
    base-image: # optional
    # List of Dockerfile paths (eg: ./Dockerfile)
    dockerfiles: # optional
    # Path of the directory to use as context (default: .)
    context: # optional, default is .
    # List of files/directories to copy inside the base image
    content: # optional
    # The entry point to set for containers based on image
    entrypoint: # optional
    # The port to expose when running containers based on image
    port: # optional
    # The working directory to use within the container
    workdir: # optional
    # List of environment variables to be set when running containers based on image
    envs: # optional
    # List of --build-args to pass to buildah.
    build-args: # optional
    # Set to true to build using the OCI image format instead of the Docker image format.
    oci: # optional, default is false
